name: zfs-buildtests

on:
  push:
  pull_request:

jobs:
  buildtests-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [18.04, 20.04]
    runs-on: ubuntu-${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Reclaim disk space
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/reclaim_disk_space.sh
    - name: Install dependencies
      run: |
        sudo apt-get update
        xargs --arg-file=${{ github.workspace }}/.github/workflows/build-dependencies.txt sudo apt-get install -qq
        sudo apt-get clean
    - name: Autogen.sh
      run: |
        ./autogen.sh
    - name: Configure
      run: |
        ./configure CFLAGS="-g -O2 -Werror"
    - name: Make
      run: |
        make -j$(nproc) --no-print-directory --silent pkg-utils pkg-kmod
